version: '2'
networks:
  pphlf:

services:
  orderer.hlf.pixelplex.io:
    container_name: orderer.hlf.pixelplex.io
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/hlf.pixelplex.io/orderers/orderer.hlf.pixelplex.io/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/hlf.pixelplex.io/orderers/orderer.hlf.pixelplex.io/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      - pphlf

  peer0.managment.hlf.pixelplex.io:
    image: hyperledger/fabric-peer
    container_name: peer0.managment.hlf.pixelplex.io
    environment:
      - CORE_PEER_ID=peer0.managment.hlf.pixelplex.io
      - CORE_PEER_ADDRESS=peer0.managment.hlf.pixelplex.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.managment.hlf.pixelplex.io:7051
      - CORE_PEER_LOCALMSPID=ManagmentMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_pphlf
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/managment.hlf.pixelplex.io/peers/peer0.managment.hlf.pixelplex.io/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/managment.hlf.pixelplex.io/peers/peer0.managment.hlf.pixelplex.io/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - pphlf

  peer0.web.hlf.pixelplex.io:
    image: hyperledger/fabric-peer
    container_name: peer0.web.hlf.pixelplex.io
    environment:
      - CORE_PEER_ID=peer0.web.hlf.pixelplex.io
      - CORE_PEER_ADDRESS=peer0.web.hlf.pixelplex.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.web.hlf.pixelplex.io:7051
      - CORE_PEER_LOCALMSPID=WebDepartmentMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_pphlf
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/web.hlf.pixelplex.io/peers/peer0.web.hlf.pixelplex.io/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/web.hlf.pixelplex.io/peers/peer0.web.hlf.pixelplex.io/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053
    networks:
      - pphlf

  peer0.ai.hlf.pixelplex.io:
    image: hyperledger/fabric-peer
    container_name: peer0.ai.hlf.pixelplex.io
    environment:
      - CORE_PEER_ID=peer0.ai.hlf.pixelplex.io
      - CORE_PEER_ADDRESS=peer0.ai.hlf.pixelplex.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ai.hlf.pixelplex.io:7051
      - CORE_PEER_LOCALMSPID=AIDepartmentMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_pphlf
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/ai.hlf.pixelplex.io/peers/peer0.ai.hlf.pixelplex.io/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/ai.hlf.pixelplex.io/peers/peer0.ai.hlf.pixelplex.io/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      - pphlf

  cli:
    container_name: pphlf-cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker/sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.managment.hlf.pixelplex.io
      - CORE_PEER_LOCAL_MSPID=ManagmentMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/managment.hlf.pixelplex.io/peers/peer0.managment.hlf.pixelplex.io/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/managment.hlf.pixelplex.io/peers/peer0.managment.hlf.pixelplex.io/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/managment.hlf.pixelplex.io/peers/peer0.managment.hlf.pixelplex.io/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/managment.hlf.pixelplex.io/users/Admin@managment.hlf.pixelplex.io/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'sleep 1000'
    volumes:
      - /var/run:/host/var/run/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./../chaincode:/opt/gopath/src/github.com/chaincode
      - ./artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/artifacts
    networks:
      - pphlf
